import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "Barbasol Can",
    description: "to sneak dino DNA cryo vials",
    price: 5000,
    categoryName: "Jurassic Park",
    imageUrl: "assets/products/barbasol.png",
    rating: 4,
  },
  {
    _id: uuid(),
    name: "Mosquito in Amber",
    description: "the OG dino founder",
    price: 3000,
    categoryName: "Jurassic Park",
    imageUrl: "assets/products/jurassic-musquito.png",
    rating: 4.2,
  },
  {
    _id: uuid(),
    name: "Raptor Resonating Chamber",
    description: "to be friends with a raptor",
    price: 1000,
    categoryName: "Jurassic Park III",
    imageUrl: "assets/products/raptor-resonating-chamber.png",
    rating: 3,
  },
  {
    _id: uuid(),
    name: "Barbasol Can",
    description: "to sneak dino DNA cryo vials",
    price: 2000,
    categoryName: "The Lost World",
    imageUrl: "assets/products/barbasol.png",
    rating: 4.5,
  },
  {
    _id: uuid(),
    name: "Mosquito in Amber",
    description: "the OG dino founder",
    price: 500,
    categoryName: "Jurassic Park",
    imageUrl: "assets/products/jurassic-musquito.png",
    rating: 5,
  },
  {
    _id: uuid(),
    name: "Raptor Resonating Chamber",
    description: "to be friends with a raptor",
    price: 800,
    categoryName: "Jurassic Park III",
    imageUrl: "assets/products/raptor-resonating-chamber.png",
    rating: 3.5,
  },
  {
    _id: uuid(),
    name: "Barbasol Can",
    description: "to sneak dino DNA cryo vials",
    price: 200,
    categoryName: "Jurassic Park",
    imageUrl: "assets/products/barbasol.png",
    rating: 1,
  },
  {
    _id: uuid(),
    name: "Mosquito in Amber",
    description: "the OG dino founder",
    price: 3500,
    categoryName: "Jurassic Park",
    imageUrl: "assets/products/jurassic-musquito.png",
    rating: 2.5,
  },
  {
    _id: uuid(),
    name: "Raptor Resonating Chamber",
    description: "to be friends with a raptor",
    price: 1200,
    categoryName: "Fallen Kingdom",
    imageUrl: "assets/products/raptor-resonating-chamber.png",
    rating: 4.4,
  },
  {
    _id: uuid(),
    name: "Barbasol Can",
    description: "to sneak dino DNA cryo vials",
    price: 5500,
    categoryName: "Jurassic World",
    imageUrl: "assets/products/barbasol.png",
    rating: 4.8,
  },
  {
    _id: uuid(),
    name: "Mosquito in Amber",
    description: "the OG dino founder",
    price: 3500,
    categoryName: "Jurassic Park",
    imageUrl: "assets/products/jurassic-musquito.png",
    rating: 2,
  },
  {
    _id: uuid(),
    name: "Raptor Resonating Chamber",
    description: "to be friends with a raptor",
    price: 4000,
    categoryName: "Jurassic Park III",
    imageUrl: "assets/products/raptor-resonating-chamber.png",
    rating: 4.7,
  },
  {
    _id: uuid(),
    name: "Barbasol Can",
    description: "to sneak dino DNA cryo vials",
    price: 400,
    categoryName: "The Lost World",
    imageUrl: "assets/products/barbasol.png",
    rating: 4.6,
  },
  {
    _id: uuid(),
    name: "Mosquito in Amber",
    description: "the OG dino founder",
    price: 2500,
    categoryName: "Jurassic Park",
    imageUrl: "assets/products/jurassic-musquito.png",
    rating: 4.1,
  },
  {
    _id: uuid(),
    name: "Raptor Resonating Chamber",
    description: "to be friends with a raptor",
    price: 900,
    categoryName: "Jurassic World",
    imageUrl: "assets/products/raptor-resonating-chamber.png",
    rating: 1,
  },
];
